dataloader:
  class: shared.dataloaders.my_csv_dataloader.MyCsvDataloader
  params: {}
  output_schema: outputs/test4/MyDataloaderOutput.yaml
preprocessors:
  - class: shared.preprocessors.uppercase_name_preprocessor.UppercaseNamePreprocessor
    params: {}
model:
  class: shared.models.mean_score_model.MeanScoreModel
  split: train
  dataloader_args: {}
  params: {}
evaluator:
  class: shared.evaluators.print_evaluator.PrintEvaluator
  params: {} 