dataloader:
  class: shared.dataloaders.my_csv_dataloader.MyCsvDataloader
  params: {}
  output_schema: outputs/test5/MyDataloaderOutput.yaml
preprocessors:
  - class: shared.preprocessors.double_score_preprocessor.DoubleScorePreprocessor
    params: {}
model:
  class: shared.models.row_count_model.RowCountModel
  split: train
  dataloader_args: {}
  params: {}
evaluator:
  class: shared.evaluators.print_evaluator.PrintEvaluator
  params: {} 