dataloader:
  class: shared.dataloaders.my_csv_dataloader.MyCsvDataloader
  params: {}
  output_schema: outputs/test6/MyDataloaderOutput.yaml
preprocessors:
  - class: shared.preprocessors.double_score_preprocessor.DoubleScorePreprocessor
    params: {}
model:
  class: shared.models.mean_score_model.MeanScoreModel
  split: train
  dataloader_args: {}
  params: {}
evaluator:
  class: shared.evaluators.score_threshold_evaluator.ScoreThresholdEvaluator
  params: {} 